### ISSUE TITLE
Test fails for `tutorial_dataset_1`

### ISSUE THREAD

**Issue by hrlai** [traitecoevo/traits.build#179]
Hi again, was unable to pass the test while following Tutorial 1:

```
> dataset_test("tutorial_dataset_1")
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 64 ]

── Error: tutorial_dataset_1 ───────────────────────────────────────────────────
<subscriptOutOfBoundsError/error/condition>
Error in `FUN(X[[i]], ...)`: subscript out of bounds
Backtrace:
    ▆
 1. └─base::sapply(metadata[["contexts"]], "[[", "context_property")
 2.   └─base::lapply(X = X, FUN = FUN, ...)
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 64 ]
```

Below is my YAML file just in case (I didn't manually fill in the unknown values.

```
source:
  primary:
    key: Tutorial_dataset
    bibtype: Article
    year: '2005'
    author: Daniel S. Falster and Mark Westoby
    journal: Journal of Ecology
    title: Alternative height strategies among 45 dicot rain forest species from tropical
      Queensland, Australia
    volume: '93'
    number: '3'
    pages: 521–535
    doi: 10.1111/j.0022-0477.2005.00992.x
    issn: 1365-2745
contributors:
  data_collectors:
  - last_name: unknown
    given_name: unknown
    ORCID: unknown
    affiliation: unknown
  assistants: unknown
  dataset_curators: unknown
dataset:
  data_is_long_format: no
  custom_R_code: .na
  collection_date: 2002-11/2002-11
  taxon_name: Species
  location_name: site
  description: unknown
  basis_of_record: unknown
  life_stage: unknown
  sampling_strategy: unknown
  original_file: unknown
  notes: unknown
locations:
  Atherton:
    site: Atherton
    description: Tropical rain forest vegetation
    latitude (deg): -17.117
    longitude (deg): 145.65
  Cape Tribulation:
    site: Cape Tribulation
    description: Complex mesophyll vine forest in tropical rain forest
    latitude (deg): -16.1
    longitude (deg): 145.45
contexts: .na
traits:
- var_in: LMA (mg mm-2)
  unit_in: unknown
  trait_name: unknown
  entity_type: unknown
  value_type: unknown
  basis_of_value: unknown
  replicates: unknown
  methods: unknown
- var_in: Leaf nitrogen (mg mg-1)
  unit_in: unknown
  trait_name: unknown
  entity_type: unknown
  value_type: unknown
  basis_of_value: unknown
  replicates: unknown
  methods: unknown
- var_in: leaf size (mm2)
  unit_in: unknown
  trait_name: unknown
  entity_type: unknown
  value_type: unknown
  basis_of_value: unknown
  replicates: unknown
  methods: unknown
substitutions: .na
taxonomic_updates: .na
exclude_observations: .na
questions: .na

```
